### ISSUE TITLE
store images for /wiki/Additional-Features

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#10]
![default](https://cloud.githubusercontent.com/assets/1638767/24499933/6b266ca8-157e-11e7-99b5-60f49ad4c22c.PNG)

**Comment by yuki-takei** [comment]
![default](https://cloud.githubusercontent.com/assets/1638767/24574513/fef50966-16ce-11e7-9907-dd95612bc28e.PNG)
![2](https://cloud.githubusercontent.com/assets/1638767/24574514/011beff2-16cf-11e7-903a-7c9bdc2d6ee3.PNG)
![3](https://cloud.githubusercontent.com/assets/1638767/24574517/02ad6fa8-16cf-11e7-8a92-071b6c0dc2c0.PNG)

**Comment by yuki-takei** [comment]
![default](https://cloud.githubusercontent.com/assets/1638767/24729267/5856ce0a-1a98-11e7-968d-b11c41237708.PNG)

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/24854470/89ed578e-1e19-11e7-90fb-f1c58e9863fd.png)

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/25067715/854ab38a-2287-11e7-90d3-ca3b6329f86f.png)

![image](https://cloud.githubusercontent.com/assets/1638767/25067722/ba45c994-2287-11e7-93a1-1b1c093ed939.png)

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/25072540/d82c2ac8-230b-11e7-9455-196881fc1094.png)

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/25239968/993c36c2-262c-11e7-8d4d-11f8c7c3b029.png)

**Comment by yuki-takei** [comment]
![search-ng](https://cloud.githubusercontent.com/assets/1638767/25486911/8e5482d4-2b9d-11e7-83a4-6ffe95d251df.png)

![search-12](https://cloud.githubusercontent.com/assets/1638767/25486915/90e8eb70-2b9d-11e7-825a-8e9b7139fa93.png)

**Comment by yuki-takei** [comment]
![gif](https://cloud.githubusercontent.com/assets/1638767/25503764/70361c7a-2bd6-11e7-8907-2dba9b7e9727.gif)

**Comment by yuki-takei** [comment]
![default](https://cloud.githubusercontent.com/assets/1638767/25566702/950d3f5c-2e19-11e7-869f-12b2af324741.PNG)

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/25870410/ed4b886e-353e-11e7-8926-1906f5a14d8b.png)

**Comment by yuki-takei** [comment]
![layout-classic-thumb](https://cloud.githubusercontent.com/assets/1638767/26466456/c6adddb4-41c9-11e7-99f2-f0333973c5b3.gif)

![layout-classic](https://cloud.githubusercontent.com/assets/1638767/26466452/c3658abc-41c9-11e7-8408-0f5bdd08b674.gif)

![layout-crowi-plus-thumb](https://cloud.githubusercontent.com/assets/1638767/26466467/ce7c0818-41c9-11e7-887b-8d1cdc6c6bbd.gif)

![layout-crowi-plus](https://cloud.githubusercontent.com/assets/1638767/26466465/cca1d16c-41c9-11e7-8d01-98c9635c3b97.gif)

**Comment by yuki-takei** [comment]
![Option](https://cloud.githubusercontent.com/assets/1638767/26511821/a1511b82-429e-11e7-8789-c0e878d49d28.png)

![Browsable](https://cloud.githubusercontent.com/assets/1638767/26511822/a2e006a2-429e-11e7-94df-a02e2a4e25a3.gif)

**Comment by yuki-takei** [comment]
![remove comment](https://cloud.githubusercontent.com/assets/1638767/26756152/4d2851bc-48d7-11e7-9524-8cf446915fba.png)

**Comment by yuki-takei** [comment]
![integrated-new-page](https://user-images.githubusercontent.com/1638767/27257317-b5fc93d4-540c-11e7-884d-47edd745a9fc.gif)

**Comment by yuki-takei** [comment]
![integrated-new-page](https://user-images.githubusercontent.com/1638767/27257377-35dade9c-540f-11e7-95d2-39c383ff5670.gif)

**Comment by yuki-takei** [comment]
![edit-from-affix](https://user-images.githubusercontent.com/1638767/27756499-0d7e8e48-5e33-11e7-954d-940f3b1600b5.png)

![edit-from-section-header](https://user-images.githubusercontent.com/1638767/27756500-0da8d4fa-5e33-11e7-9210-bdebb8c4ec8a.png)

**Comment by yuki-takei** [comment]
![image](https://user-images.githubusercontent.com/1638767/28246790-1357218c-6a5d-11e7-883b-c995360047d9.png)

**Comment by yuki-takei** [comment]
![dev-demo](https://user-images.githubusercontent.com/1638767/29137066-12fdc346-7d7a-11e7-901e-f81cc3785c7d.gif)

![dev-demo-full](https://user-images.githubusercontent.com/1638767/29137077-1d9aa2b0-7d7a-11e7-9ca1-c68176640b47.gif)

**Comment by yuki-takei** [comment]
![dev-demo-full](https://user-images.githubusercontent.com/1638767/29144180-ee00e28a-7d92-11e7-8678-16f1c99b8536.gif)

![dev-demo](https://user-images.githubusercontent.com/1638767/29144176-ec7cac6e-7d92-11e7-87b9-ad45a3ad6e49.gif)

**Comment by yuki-takei** [comment]
![rename](https://user-images.githubusercontent.com/1638767/29178517-c2a78b44-7e2c-11e7-9ab1-6dde65a18a8b.png)

![delete](https://user-images.githubusercontent.com/1638767/29178542-d5a0319c-7e2c-11e7-94f9-46271a73346b.png)

**Comment by yuki-takei** [comment]
![image](https://user-images.githubusercontent.com/1638767/33528400-221f0720-d8a3-11e7-8dc7-0465fc3e26b1.png)

**Comment by yuki-takei** [comment]
![image](https://user-images.githubusercontent.com/1638767/33528412-447d5bdc-d8a3-11e7-8cb7-d6208ac8f35a.png)

**Comment by yuki-takei** [comment]
![Highlight Terms](https://user-images.githubusercontent.com/1638767/35504348-2fb4336a-0526-11e8-81b9-2579b2cae862.gif)

**Comment by yuki-takei** [comment]
![Shortcuts Help](https://user-images.githubusercontent.com/1638767/35505391-5a38ff32-0529-11e8-9d82-014a7bf4ef34.png)

**Comment by yuki-takei** [comment]
![Shortcuts Help](https://user-images.githubusercontent.com/1638767/35505428-74321748-0529-11e8-82df-12e2d4341b93.png)

**Comment by yuki-takei** [comment]
![Theme Selector](https://user-images.githubusercontent.com/1638767/35506125-9fafc6ca-052b-11e8-811f-b842e34f59bb.gif)

**Comment by ryu-sato** [comment]
![crowi-plus-searchable-page-name-inputter](https://user-images.githubusercontent.com/32702772/35512909-a895601a-0544-11e8-94f0-3f42438f314a.gif)

**Comment by yuki-takei** [comment]
![logo-letter](https://user-images.githubusercontent.com/1638767/41856849-0b7a0898-78d1-11e8-9dba-1b89d4063632.png)

used by Google APIs

**Comment by yuki-takei** [comment]
![hackmd-integration](https://user-images.githubusercontent.com/1638767/43729131-3f87977c-99e2-11e8-9c4c-9bf75e226fce.gif)

**Comment by yuki-takei** [comment]
![edit table with gui](https://user-images.githubusercontent.com/1638767/46668760-615ba200-cc08-11e8-821a-d8b17f3fc255.gif)

**Comment by yuki-takei** [comment]
![edit table with gui 2](https://user-images.githubusercontent.com/1638767/47561167-78fb9000-d955-11e8-8d8b-7a670ed8e5f3.gif)

**Comment by yuki-takei** [comment]
![refs](https://user-images.githubusercontent.com/1638767/64986526-1b23be00-d902-11e9-9e33-65ad15767920.gif)
![refsimg](https://user-images.githubusercontent.com/1638767/64986528-1c54eb00-d902-11e9-95dc-2784fa15746c.gif)
![lightbox](https://user-images.githubusercontent.com/1638767/64986530-1e1eae80-d902-11e9-8711-b5df3572769c.gif)

**Comment by yuki-takei** [comment]
<img width="322" alt="add-to-this-channel" src="https://user-images.githubusercontent.com/1638767/135658794-a8d2dbc8-580f-4203-b368-e74e2f3c7b3a.png">

**Comment by satof3** [comment]
![dockerhub](https://github.com/user-attachments/assets/1a82236d-5a85-4a2e-842a-971b4c1625e6)

**Comment by satof3** [comment]
![Image](https://github.com/user-attachments/assets/0acf1409-cea7-4f0e-841c-af5bd8be6711)
