### ISSUE TITLE
Bug: Can't upload profile image

### ISSUE THREAD

**Issue by hogewest** [weseek/crowi-plus#107]
Environment
------------

- [OS] Mac OSX 
- [crowi-plus] 1.2.9-RC
- [node.js] 6.7.0
- [browser] Chrome 60.0.3112.40

How to reproduce? (再現手順)
---------------------------

1. move `/me`
1. choose image file

What happens? (症状)
---------------------

- can't upload image file

![cap](https://user-images.githubusercontent.com/140791/27694533-4fdbe66c-5d27-11e7-96aa-a5411e3d2223.gif)

What is the expected result? (期待される動作)
-------------------------------------------

- image can be uploaded

**Comment by yuki-takei** [comment]
This bug was fixed in [v1.2.9](https://github.com/weseek/crowi-plus/releases/tag/v1.2.9).
