### ISSUE TITLE
Bug(Derived from the official): Firefoxで開いた編集画面からCtrl+(Shift+)Tabでブラウザタブを切り替えるとインデントが増減する

### ISSUE THREAD

**Issue by tats-u** [weseek/crowi-plus#132]
Environment
------------

- [OS] サーバ: Alpine Linux on Docker 17.06 on Ubuntu 16.04
- [crowi-plus] 1.1.12
- [node.js] 6.10.3 (Docker付属)
- [browser] Firefox 54.0.1 (Chrome 59・IE11では再現なし)

How to reproduce? (再現手順)
---------------------------

1. Firefoxで複数のタブを開く
2. タブの1つでWikiにアクセスし、適当なページの編集画面に入る
3. 編集画面のエディタをアクティブにする (エディタにフォーカスを合わせる)
4. Ctrl+Tab・Ctrl+Shift+Tabで前後のタブに切り替える (マウスクリックによるタブ切り替えでは再現しません)

What happens? (症状)
---------------------

- Ctrl+Tabで次のタブに切り替えるとインデントが増える
- Ctrl+Shift+Tabで前のタブに切り替えるとインデントが減る

What is the expected result? (期待される動作)
-------------------------------------------

-  Ctrl+(Shift+)Tabでタブを切り替えてもインデントの増減が起こらない

Note
----

恐らくフロントエンドの仕様とFirefoxの仕様が噛み合わずに起こった結果だと思います。よろしくお願いします。

**Comment by yuki-takei** [comment]
@tats-u 
なるほど、確かに。

こちら本家 Crowi 由来の挙動なので、お手数ですが一旦本家側に修正依頼投げてもらえないでしょうか。
原因箇所この辺りになります。
https://github.com/crowi/crowi/blob/master/resource/js/crowi-form.js#L177

対応されたバージョンがリリースされれば crowi-plus も取り込みます。
「対応する予定がない」という返答があればその場合はこちらで対応しようと思います。

**Comment by tats-u** [comment]
素早いご対応ありがとうございました。本家の方にもIssueを投げておきました。

**Comment by yuki-takei** [comment]
本家の master に入ってきてたのをとりあえず cherry-pick して入れて v2.0.1 としてリリースしました。ご確認ください。

**Comment by tats-u** [comment]
ありがとうございます。あとはDocker側の更新を待つことにします。
本家のデモWiki (http://demo.crowi.wiki/) ではまだ問題が直っていないのが気がかりですが・・・

**Comment by yuki-takei** [comment]
本家デモで直ってないのは気にしなくていいかと。

向こうは次の v1.6.3 で当該 issue の修正を入れる予定のようですが、実はまだリリースされていません。(なので当然デモにも反映されていない)

こちらも元々本家の次のバージョンのリリースを待ってマージする予定でしたが、この issue の修正自体は軽微だったので、まあリリース待つまでもないかという判断でその部分だけ取り込んで、今回の crowi-plus v2.0.1 のリリースに先行して乗っけた、というのが現在の状況です。
