### ISSUE TITLE
ショートカットで保存しようとするとエラー

### ISSUE THREAD

**Issue by imagepit** [weseek/crowi-plus#157]
大変便利なWikiシステムを公開して頂き感激しております。
しかし、私の下記の環境でdocker-composeを使い、crowi-plusを構築したのですが、ショートカットの保存をしようとすると下記のエラーが出てしまいます。

![](https://www.evernote.com/l/AB1ucx0Pa1FDnZihWvkws2NzGJ5y61ZcoEYB/image.png)

```
Error: Error: Page exists
    at app.4a667c8e37c836c3181e.bundle.js:1
    at <anonymous>
(anonymous) @ legacy-form.ca3a219fbda5df013f4e.bundle.js:1
```

## 環境

OS | Mac OS 10.11.6
---|---
Docker for Mac | 17.06.0
crowi-plus | 2.0.7
node.js	| 6.10.3
npm | 4.6.1
yarn | 0.24.4

ちなみに、私の環境はnginxでリバースプロキシ経由でアクセスしていますので、nginxでの設定内容もお伝えいたします。

**nginx.conf**

```
    server {
        listen 80;
        server_name wiki.xxxx.net;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_set_header  Host            $host;
            proxy_set_header  X-Real-IP       $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_max_temp_file_size 0;
        }
        access_log  /Users/xxxx/Documents/nginx/xxxx.access.log;
        error_log  /Users/xxxx/Documents/nginx/xxxx.error.log;
    }
```

ちなみにnginxを経由しないでそのままアクセス`localhost:3000`して試してみましたが、同様のエラーが出ますのでnginxのせいではない気がしています。

お手数ですがご確認よろしくお願いします。

**Comment by yuki-takei** [comment]
ううむ…再現せず…

こちらの動作環境書きます。

Environment
-------------

### 動作環境

- docker on Ubuntu
    - 17.03.1-ce, build c6d412e
- crowi-plus 2.0.7 (docker-compose による起動)
    - コンテナ内 node.js 6.10.3
    - コンテナ内 npm 4.6.1
    - コンテナ内 yarn | 0.24.4

### テスト環境

- OS
    - Windows 10
- ブラウザ
    - Firefox 54.0.1 64bit on Windows 10
    - Google Chrome 60.0.3112.90 64bit on Windows 10

試したこと1
-----------

1. `/hoge/fuga` を作成
1. 一旦右下の「Update Page」で保存
1. 再度 `/hoge/fuga` を編集
1. 適当に内容を変更して Ctrl+S

試したこと2
-----------

1. `/hoge/fuga` を作成
1. Ctrl+S で保存
1. 再度 `/hoge/fuga` を編集
1. 適当に内容を変更して Ctrl+S

結果
-----

Mozilla, Chrome 共に正常に保存された。

**Comment by yuki-takei** [comment]
@imagepit 
今分かってるのは動作環境、テスト環境共にOSが違うって感じですね。
上で書いた「試したこと」のような手順で、100% 再現する手順ってありますか？

Slack の crowi-plus Team で「ローカルでの起動だと再現した」という人もいたので、こちらでも環境と手順聞いてみますね。

**Comment by yuki-takei** [comment]
続報。動作環境依存っぽいです。

[OK] crowi-plus on Docker on Ubuntu
[OK] crowi-plus on Docker on Ubuntu on VirtualBox on Win
[NG] crowi-plus on Docker on Mac

どういうわけか、サーバー側が Mac の時に限り、クライアントコードの

https://github.com/weseek/crowi-plus/blob/master/resource/js/legacy/crowi-form.js#L432

が else に入ってしまうという…謎。
因みに `pageId` は
https://github.com/weseek/crowi-plus/blob/master/resource/js/legacy/crowi-form.js#L1
のように取得しているけれど、ブラウザのJSコンソールから同様の jQuery コードを叩いてみてもちゃんと ID 取れる。ますます謎。

**Comment by yuki-takei** [comment]
[v2.3.5 以降で CodeMirror を採用した](https://github.com/weseek/crowi-plus/blob/master/CHANGES.md#235) ので、解決していると信じたい。要確認。

**Comment by Tatsuki-I** [comment]
2.3.8で直っている事を確認しました.

**Comment by yuki-takei** [comment]
ありがとうございます！close します。
