### ISSUE TITLE
デモページが502 Bad Gateway

### ISSUE THREAD

**Issue by tats-u** [weseek/crowi-plus#158]
先程デモページを見ようとしたところ502 Bad Gatewayになっていて閲覧できませんでした。バックエンドのCrowi-plus本体が落ちていると思われますので、Dockerコンテナならば再ビルド及び再起動を、そうでないなら再デプロイをよろしくお願いします。

**Comment by yuki-takei** [comment]
コンテナ落ちてたので上げておきました。ありがとうございました。
ping 監視とかした方がいいのかなあ…
