### ISSUE TITLE
The plan "undefined" for the addon "bonsai" does not exist.

### ISSUE THREAD

**Issue by Ryu236** [weseek/crowi-plus#161]
Herokuを使用しDeploy to HerokuボタンよりCrowi-plusを利用しようと思ったのですが、herokuのサイトに移動するとSomething went wrong:
The plan "undefined" for the addon "bonsai" does not exist. Please ensure that the plan is spelled correctly. とエラーが出ます。
また、Deploy appよりHerokuのアプリを作成すると、Configure environmentのところでCouldn't find either the add-on service or the add-on plan of "bonsai". とエラーが出てアプリが作成できません。

**Comment by yuki-takei** [comment]
再現確認しました

**Comment by yuki-takei** [comment]
@Ryu236 修正完了しました。master ブランチからであればディプロイ可能になったと思います。

ご報告ありがとうございました。
