### ISSUE TITLE
Bug: インラインコードに日本語を入力すると、表示がずれる

### ISSUE THREAD

**Issue by skomma** [weseek/crowi-plus#165]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|crowi-plus|2.0.8|
|node.js   |6.10.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10, OS X El Capitan|
|browser   |Firefox 54.0.1/Chrome 59.0 (on Mac)|
||Firefox ESR 52.3.0/Chrome 60.0 (on Win)|

How to reproduce? (再現手順)
---------------------------

1. ページを作成し、以下の文字列をダブルクォートを使い、入力する
```
aaaabbbbccccdddd
    aaaabbbbcccc
ああああいいいい
```

What happens? (症状)
---------------------

- 日本語を入力した行だけ表示がずれる
  - 日本語だけプロポーショナルフォントになってる？

What is the expected result? (期待される動作)
-------------------------------------------

- 日本語を入力しても表示がずれない

Screen shots
----

- Firefox on Windows
![firefox_win](https://user-images.githubusercontent.com/4454401/30132537-a5f6f628-938b-11e7-836b-57f15457eaa4.png)
- Chrome on Windows
![chrome_win](https://user-images.githubusercontent.com/4454401/30132547-b005845e-938b-11e7-9e57-03cba8b0c159.png)
- Firefox on Mac
![firefox_mac](https://user-images.githubusercontent.com/4454401/30132570-c4d234ea-938b-11e7-9f84-5de8f70d8d56.png)
- Chrome on Mac
![chrome_mac](https://user-images.githubusercontent.com/4454401/30132577-cd1969c0-938b-11e7-8552-c1775a49d936.png)

**Comment by yuki-takei** [comment]
Mac 持ってないのでテストをお願いしたいです。

```
font-family: Monaco, Menlo, Consolas, "Courier New", Osaka-Mono, "MS Gothic", monospace;
```

入れたらどうなりますかね。

**Comment by yuki-takei** [comment]
Crowi 使うのはどうせエンジニアでしょ、っていう前提から入って、ローカルに入ってることが期待されるコーディングフォントを並べるっていう手もあるかもしれない。。

```css
font-family: "SourceHanCodeJP-Regular",
               "M+ 1m",
               "Rounded M+ 1m regular",
               "Rounded M+ 2m regular",
               "Rounded Mgen+ 1m regular",
               "Rounded Mgen+ 2m regular",
               "Yutapon coding Regular",
               "Myrica M",
               "MyricaM M",
               "Ricty Diminished Discord",
               "Ricty Diminished",
               "Migu 1M",
               "Migu 2M",
               "VL ゴシック",
               "MeiryoKe_Gothic",
               Monaco, Menlo, Consolas,
               monospace;
```

**Comment by haruhikonyan** [comment]
とりあえず上記2つではズレる

**Comment by haruhikonyan** [comment]
```
Osaka-Mono, "MS Gothic", Monaco, Menlo, Consolas, "Courier New", monospace
```
上記でズレない
