### ISSUE TITLE
Improve: Selective batch deletion in search result page

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#168]
Target Page
-------------

https://demo.crowi-plus.org/_search?q=Sandbox

TODO
-------

* delete completely
* i18n

**Comment by yuki-takei** [comment]
"DeletionMode" は、"Select to delete" に。日本語では「選択して削除」

**Comment by TatsuyaIse** [comment]
日本語化以外の修正が完了しました。

**Comment by TatsuyaIse** [comment]
![demosearchselectdeletion](https://user-images.githubusercontent.com/8895367/31264570-03be0dac-aaa5-11e7-8ca2-94d6ed3219cc.gif)
デモGIF
