### ISSUE TITLE
アップデートするとプラグインが効かない

### ISSUE THREAD

**Issue by dev-hayash** [weseek/crowi-plus#174]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|crowi-plus|2.0.10 -> 2.1.0|
|node.js   |6.11.0|
|npm       |5.4.2|
|Using Docker|no|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|no|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10(64bit)|
|browser   |Firefox 55.0.3|

How to reproduce? (再現手順)
---------------------------

1. 起動中のcrowi-plusを停止

```bash
sudo su -
systemctl stop crowi-plus
```

2. npmの更新(もともとは4.6.1)

```bash
yarn global add npm@5    
```

3. 最新ソースの取得

```bash
git pull
```

4. pluginの更新

```bash
yarn add   crowi-plugin-lsx
yarn add   crowi-plugin-pukiwiki-like-linker
yarn
```

5. ビルド

```bash
npm start
```

What happens? (症状)
---------------------

- アップデート前に作成していたページ内の`$lsx(.)`がそのままの文字で表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- 指定パス配下のページを出力

screen shot
----
* $lsxがそのまま出てしまう
![default](https://user-images.githubusercontent.com/19341340/30949598-5b5221ce-a452-11e7-9521-cbf7bf8e0039.PNG)

* package.jsonにはpluginの記述はある
![2](https://user-images.githubusercontent.com/19341340/30949621-77d61468-a452-11e7-8c9b-69a4b0b113f0.PNG)

**Comment by yuki-takei** [comment]
@dev-hayasi
ご報告ありがとうございます。

まだこちらで再現するかどうか確認取れてないのですが、2.0.10, 2.1.0 共にリリースされていないので、master ブランチを参照して 2.1.0-RC を運用されているのだと推測します。

動作させているコミットハッシュを教えていただけますでしょうか。

**Comment by yuki-takei** [comment]
@dev-hayash
ご報告ありがとうございます。

まだこちらで再現するかどうか確認取れてないのですが、2.0.10, 2.1.0 共にリリースされていないので、master ブランチを参照して 2.1.0-RC を運用されているのだと推測します。

動作させているコミットハッシュを教えていただけますでしょうか。

**Comment by dev-hayash** [comment]
御推測の通り、2.1.0-RCです。
コミットハッシュは以下になります。
612a17ba25560810901bf87019880c3c1aa8e119

**Comment by dev-hayash** [comment]
RC版にissueしてお手間をかけてしまい申し訳ありません。
ad58e90d0ecc8d7496819e18dcfae4b6e630599f を入れてみます。

**Comment by dev-hayash** [comment]
ad58e90d0ecc8d7496819e18dcfae4b6e630599f をcheckoutして試したところ正常に機能しました。

**Comment by yuki-takei** [comment]
了解です。 612a17b  に問題があるというのがわかって助かりました。

**Comment by yuki-takei** [comment]
[crowi-plugin-lsx](https://github.com/weseek/crowi-plugin-lsx) の v1.3.6 をリリースしました。
プラグイン側も合わせてアップデートすることで、 612a17b 以降でも動くようになります。

**Comment by dev-hayash** [comment]
対応ありがとうございます。
