### ISSUE TITLE
Feature: Tree View Support

### ISSUE THREAD

**Issue by Cilvia** [weseek/crowi-plus#175]
crowi-plusを個人wikiとして活用させていただいております。
使っていた上で、ページ一覧機能のリスト表示やタイムライン表示では、関連ページ(上位・下位など)への移動がしにくい・一覧が体系的でないために見辛い、といった問題があると感じています。
そのため、ページのツリービュー機能(ConfuluenceのサイドバーのPagesのようなもの) があればより使いやすくなると思います。

ご検討のほど、よろしくお願いいたします。

**Comment by yuki-takei** [comment]
@Cilvia ご感想ありがとうございます。

一応、下のスクリーンショットのような機能は [crowi-plugin-lsx](https://github.com/weseek/crowi-plugin-lsx) というプラグインで実現可能です。

![image](https://user-images.githubusercontent.com/1638767/31005600-6e40d838-a534-11e7-9c8e-50724e4a96d6.png)

「ConfuluenceのサイドバーのPagesのようなもの」との違いを挙げるとすれば、

* 開閉できない(collapse できない)
* そもそもサイドバーがないので、全てのページからアクセスできるツリー表示が存在しない

の2点でしょうか。どちらも issue は立っていませんが、後者は要望で聞いたことがある気がします。
