### ISSUE TITLE
Improve: Suspend account

### ISSUE THREAD

**Issue by shield-9** [weseek/crowi-plus#179]
初めてインストールした際、パスワードの再発行を試そうとして、誤って「アカウント停止」をクリックしてしまいました。
ほかの管理者を追加する前だったので、DBを書き換えて修正しましたが、「自分自身のアカウントを停止できない」という制約があるとよいのではないでしょうか。

**Comment by yuki-takei** [comment]
@shield-9 確かにそうですね。近々修正します。

**Comment by yuki-takei** [comment]
v2.1.2 リリースで搭載されます。
