### ISSUE TITLE
Bug: Styling of user edit menu

### ISSUE THREAD

**Issue by shield-9** [weseek/crowi-plus#180]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.3|
|crowi-plus|2.0.9|
|node.js   |6.11.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 (1703) 15063.608|
|browser   |Google Chrome 62.0.3202.38, Microsoft Edge 40.15063.0.0|

How to reproduce? (再現手順)
---------------------------

1. http://{your_crowi_host}/admin/users にアクセスする
1. "Edit" (編集) をクリックする

What happens? (症状)
---------------------

編集メニューの下部分がフッターに被ってしまう
![Current](https://user-images.githubusercontent.com/3660715/31048089-2e5ef1aa-a651-11e7-866a-dda40f931c97.png)

What is the expected result? (期待される動作)
-------------------------------------------

編集メニューの下部分がフッターに被らない
![Expected](https://user-images.githubusercontent.com/3660715/31048185-34bdc178-a653-11e7-9095-c00982025242.png)

**Comment by yuki-takei** [comment]
@shield-9 ご報告ありがとうございます。

こちら c94f837 で別機能実装時についでに直している([single.html](https://github.com/weseek/crowi-plus/commit/c94f837e034cf5c331e7a47b9ca0209c7b3dae83#diff-c961a2740dd951efb39928398491ba37R21))ので、次回リリース時に反映される予定です。

**Comment by yuki-takei** [comment]
[v2.1.0](https://github.com/weseek/crowi-plus/releases/tag/v2.1.0) リリースしました。
