### ISSUE TITLE
ユーザーIDにピリオドを利用可能としたい

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#186]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.4.1708 (Core)|
|crowi-plus|2.1.1|
|node.js   |6.11.3|
|npm       |4.6.1|
|Using Docker|no|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------

1. 初回ログイン時ユーザ情報入力画面を表示( `/login/invited` ）
1. ユーザIDに `.` ピリオドを含めて登録

What happens? (症状)
---------------------

- 以下のエラーとなり登録できない
 `invitedForm.username has invalid characters`

What is the expected result? (期待される動作)
-------------------------------------------

- `.` ピリオドを含めたユーザIDで登録したい。

Note
----
- 管理者のユーザID登録では`.`ピリオドを含めたユーザIDが登録できるため、入力チェックだけの問題と思われる。

**Comment by yuki-takei** [comment]
@takuma-watanabe 
仰る通り、invite 時のみフォームの validation で `.` が許容されていませんでしたので、登録時と揃えて `.` を使えるように修正しました。 v2.1.2 で利用可能になります。

**Comment by takuma-watanabe** [comment]
ご連絡漏れていましたが、対応頂きありがとうございました。
