### ISSUE TITLE
Improve: ページ作成時に特殊文字(^ $ * + 等)の利用を可能にする

### ISSUE THREAD

**Issue by suicabar** [weseek/crowi-plus#192]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS|
|crowi-plus|2.2.0|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac/Windows|
|browser   |Chrome 最新|

Note
----
先日crowi-plusを導入させて頂いたのですが、
C++というページを作製したところ、正常に作成できずNot Found状態になってしまします。
実体参照でC%2B%2Bと試しに入力しても同じ結果でした。
本家側の問題な気もしますが、あちらは導入しておらず不明でしたので一応ご報告させて頂きます。

**Comment by yuki-takei** [comment]
@suicabar ポストとご報告ありがとうございます。

調査と結果
------------

crowi-plus と 本家のデモ(http://demo.crowi.wiki/)の両方で再現を確認しました。
特に何もアラートなどが出ないのがちょっと不親切ではあるのですが、本家から引き継いでいる仕様になります。

https://github.com/crowi/crowi/blob/master/lib/models/page.js#L382

に `+` が入っているのが許可されていないのが原因です。試しに開発環境(crowi-plus)で該当箇所を消すと、正常に作成と閲覧できることを確認しました。

今後の対応について
---------------------

この問題はちょっと判断が難しく…
長くなりますが自分のメモとしても現状分かっていることとを残しておきます。

本家の仕様で `^ $ * +` あたりを禁止している理由としては、「これらの文字をURLに入れると正規表現的にページを検索してリスト表示できる」という機能があるためです。デモサイトで

http://demo.crowi.wiki/user/test.*/

にアクセスしてみるとわかりますが、頭に `test` と付くユーザーページをリストしてくれます。
これは本家仕様としてはかなり大事なものだと以前メンテナの方が仰っていたので、リクエストしても仕様を変えたくないと判断される可能性が高いです。

因みに `+` だけではなく、ページ名に `()` や `{}` を含んだ場合、作成はできますが、特に `/` で終わるURLにアクセスした場合に独特の動きをします。しかしそれが仕様です。

一方、実は crowi-plus ではこの機能は働きません。(！)
我々の会社では設定として「crowi-plus Simplified Behavior」のみで利用していますが、その実装時にないほうが都合が良かった(どうせ`/`で終わるURLは使わないし、`()`や`{}`を含むページもシンプルにページとして扱いたかった)ので働かないようにしました。REST API はデータ取得のみの用途なので、本家と同様の動作をするようになっています。つまり REST API でのみ正規表現の利用が可能。

上記のような改修を行っているので、crowi-plus では、当該行を修正して `^ $ * +` あたりを利用できるようにはできます。ただデータの互換性がなくなってしまうので、そういったページを作った後、crowi-plus から本家 crowi に戻った場合にはその辺りがうまく動かなくなってしまいます。

なので、crowi-plus として、データの後方互換性を失っても `^ $ * +` を使えるようにするか？
という話になりますが…管理者が選択できるオプションとして搭載するべきなのかもしれませんね。

**Comment by yuki-takei** [comment]
急務ではないので一旦 close します。
