### ISSUE TITLE
Improve: Ensure that admin users can remove users waiting for approval

### ISSUE THREAD

**Issue by naoki0913** [weseek/crowi-plus#194]
こんにちは。

少し前からCrowi-plusを社内で導入したのですが、「ユーザ登録が承認制の場合、申請の取り下げができず、一度承認しなければならない」という点が少々気になっております。
間違えて申請してしまった場合や、不審な申請は取り下げられるようなると良いと思ったので、もし可能でしたら「登録申請取り下げ」機能を実装していただけるとありがたいです。

お手数ですが、ご検討のほどよろしくお願いいたします。

**Comment by yuki-takei** [comment]
@naoki0913 

やっつけですが、承認待ちユーザーを管理画面から削除可能にしました。
v2.2.1 で利用可能です。

![image](https://user-images.githubusercontent.com/1638767/32104264-9fd61256-bb5e-11e7-97ce-43312448163d.png)

**Comment by naoki0913** [comment]
@yuki-takei 
お早いご対応ありがとうございます。
非常に感謝しております。
今後ともよろしくお願いいたします。
