### ISSUE TITLE
Bug: ヘッダーの検索バーに検索語を入れて検索しても、URLのクエリにパラメータとして反映されない

### ISSUE THREAD

**Issue by MakoTano** [weseek/crowi-plus#209]
crowi-plus 2.2.3 で「ヘッダーの検索バーに検索語を入れて検索しても、URLのクエリにパラメータとして反映されない事象」が起きています。、`https://demo.crowi-plus.org/` でも同様の事象が確認できました。
実際に検索もできていない状況です

Environment
------------
### Host

| item     | version |
| ---      | --- |
|OS        |centos7|
|crowi-plus|2.2.3|
|node.js   |6.11.5|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac|
|browser   |chrome（現時点最新）|

How to reproduce? (再現手順)
---------------------------

1. ヘッダーの検索バーに検索語を入れて検索をする
1. URLのクエリにパラメータとして反映されない
1. 実際に検索もできていない

What happens? (症状)
---------------------

- URLのクエリパラメータへ検索語が反映されない
- 実際に検索もできていない

What is the expected result? (期待される動作)
-------------------------------------------

- URLのクエリパラメータへ検索語が反映される 
- 実際に検索もできる

Note
----

- [Slackにて報告させて頂いた事象です ](https://crowi-plus.slack.com/archives/C4V5ZG4UC/p1512441029000142)

**Comment by yuki-takei** [comment]
@MakoTano ご報告ありがとうございます。再現確認しました。
[c1695da] で react-bootstrap-typeahead をアップグレードしたときに混入したバグでした。次回リリース時に修正します。

**Comment by MakoTano** [comment]
ありがとうございます！！
