### ISSUE TITLE
BugFix: The XSS Library escapes inline code blocks

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#226]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.3.1|
|node.js   |6.12.2|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Vivaldi 1.13.1008.40 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1.  Wiki の内容に以下を記載する

```
`<test>このような</test>内容を記載する`
```

What happens? (症状)
---------------------

- 以下のように表示され、`<test>`および`</test>`が表示されない

```
このような内容を記載する
```

また、inline code では `&lt;` `&gt;` を記載しても実態参照にならないので、タグが表記できない。

What is the expected result? (期待される動作)
-------------------------------------------

- 以下のようにタグを含めて表示されること

```
<test>このような</test>内容を記載する
```

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございます。
#215 のXSS対応で発症した問題のようです。ちょっと対策考えます。

**Comment by yuki-takei** [comment]
@takuma-watanabe 修正をコミットしました。次回リリースをお待ちください。

**Comment by takuma-watanabe** [comment]
対応ありがとうございました！
