### ISSUE TITLE
Bug: Couldn't invite users(failed to create)

### ISSUE THREAD

**Issue by kazuemon** [weseek/crowi-plus#230]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 16.04 |
|crowi-plus| 2.3.2 |
|node.js   | 6.12.2 |
|npm       | 4.6.1 |
|Using Docker| yes |
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]| yes |

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

nginxでリバースプロキシさせています。
SSL適応しています。

ユーザーは招待制で、管理ユーザーは正常に登録できています。

一応[こちら](https://nukkit-jp.ga/)で動作中です

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 7 |
|browser   | Google Chrome |

How to reproduce? (再現手順)
---------------------------

1.crowi-plus-docker-composeの[Install and Start](https://github.com/weseek/crowi-plus-docker-compose#install-and-start)通りセットアップ
2.Wiki管理画面→ユーザー管理→新規ユーザーの招待→アドレス入力(招待をメールで送信はチェック外す)→招待する→作成失敗

What happens? (症状)
---------------------

![2018-01-09 15_56_37- nukkitjapanwiki](https://user-images.githubusercontent.com/12812934/34719591-ba8417ce-f57e-11e7-9e1c-b76b13ef5fa7.png)

エラーなどは出力されていません。
また、プラグインは一つも導入していない状態でも導入しても変わりありません。

**Comment by yuki-takei** [comment]
@kazuemon ご報告ありがとうございます。再現確認してみます。

**Comment by yuki-takei** [comment]
@kazuemon 再現確認しました。crowi-plus 独自実装で混入したバグでした。報告いただいて助かりました。

この後修正した v2.3.3 をリリースします。ご確認ください。

**Comment by kazuemon** [comment]
@yuki-takei 
了解しました。ありがとうございます。
