### ISSUE TITLE
相対パスの動作がおかしい(気がする)

### ISSUE THREAD

**Issue by Tatsuki-I** [weseek/crowi-plus#233]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|crowi-plus|x.y.z|
|node.js   |2.3.2|
|npm       |6.12.2|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Chrome|

What happens? (症状)
---------------------

[最強のWiki「Crowi」のフォーク、「crowi-plus」を公開した話](https://qiita.com/yuki-takei/items/5df9601039ccfc1df01f#pukiwiki-%E3%81%8B%E3%82%89-crowi-%E3%81%B8) にある通り, 相対パスを使ってリンクを設定しましたが, 期待する動作が得られませんでした.

`hoge/parent/child1` にて `../child2` とリンクを記述すると, `hoge/child2` に飛んでしまいます.

また, `./` を指すと親に飛んでしまいます.

恐らく相対パスが全て1つ親を差しているものと考えられます.

デモサイト内の [こちら](https://demo.crowi-plus.org/user/tatsuki/memo/2018/01/11/parent/child1) に上記の構造のページを作ってありますので, こちらで症状が確認できます.

What is the expected result? (期待される動作)
-------------------------------------------

[最強のWiki「Crowi」のフォーク、「crowi-plus」を公開した話](https://qiita.com/yuki-takei/items/5df9601039ccfc1df01f#pukiwiki-%E3%81%8B%E3%82%89-crowi-%E3%81%B8) にある通り, `hoge/parent/child1` にて`../child2` とすると `hoge/parent/child2`のリンクに飛ぶという動作.

**Comment by yuki-takei** [comment]
@Tatsuki-I デモサイトのページを確認しました。
Markdown 標準の記法を使うと、そのような動作になってしまいますね。

```markdown
[child2](../child2)
[child1](./)
```

は、`hoge/parent/child1` からはそれぞれ `hoge/child2` および `hoge/parent` にリンクします。

そのために作ったのが [weseek/crowi-plugin-pukiwiki-like-linker](https://github.com/weseek/crowi-plugin-pukiwiki-like-linker) で、

```markdown
[[child2>../child2]]
[[child1>.]]
```

と書くことで、それぞれ `hoge/parent/child2` と `hoge/parent/child1` にリンクします 😃

**Comment by Tatsuki-I** [comment]
@yuki-takei 
なるほど、そういう事だったんですね
ありがとうございます
