### ISSUE TITLE
Bug: プレビュー時に bootstrap3 の `alert alert-info` クラスを適用した dom が表示されない

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#234]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.3.3|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Vivaldi 1.13.1008.40 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1. 任意のページを編集し、以下を記載。
```
<div class="alert alert-success" role="alert"><strong>success</strong>：　成功しました系メッセージ。</div>
<div class="alert alert-info" role="alert"><strong>info</strong>：　お知らせ系メッセージ。</div>
<div class="alert alert-warning" role="alert"><strong>warning</strong>：　警告系メッセージ。</div>
<div class="alert alert-danger" role="alert"><strong>danger</strong>：　最重要メッセージ。</div>
```
1. 右側のプレビューを確認する

What happens? (症状)
---------------------

- `alert-info` クラスのみプレビューに表示されない

![image](https://user-images.githubusercontent.com/32568002/34972537-7cf951c0-fac5-11e7-9db5-94b72c09fed8.png)

- プレビューされないだけで、保存すれば正しく表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- `alert-info` クラスもプレビュー表示される

Note
----

デモサイトの以下のページで再現します。
[/Sandbox/bootstrap](https://demo.crowi-plus.org/5a5c05ba582ef4003093a3bb)

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございます。再現確認しました。本家由来のバグのようです。
近々修正します。

**Comment by yuki-takei** [comment]
@takuma-watanabe 修正をコミットしました。次回リリースをお待ちください。

**Comment by takuma-watanabe** [comment]
2.3.6 で確認しました！
ありがとうございました。
