### ISSUE TITLE
HTMLタグで囲むと無効となるMarkdown記法がある

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#235]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.3.3|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](crowi-plus-docker-compose)|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Vivaldi 1.13.1008.40 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1. Wikiページに以下の記載を行う。
```
<p>
- リストに
- ならない
</p>
```

What happens? (症状)
---------------------

- Markdownが無効化（？）され、ブラウザに以下のように表示される。

```
- リストに - ならない
```

ソースを確認すると以下のHTMLとなっている。
```
<p>
- リストに
- ならない
</p>
```

What is the expected result? (期待される動作)
-------------------------------------------

- Markdown によるリスト表示が行われてほしい
- 本リスト記法に限らず、テーブル記法やコードブロック等も無効となるようなので、それらも有効となって欲しい

Note
----

- 以下のデモページで確認が可能です。
/Sandbox/bootstrap
https://demo.crowi-plus.org/5a5c05ba582ef4003093a3bb
-  `**Bold**` や `*Em*` 、`~~取消~~` などは有効なようで、有効化されるMarkdown記法とそうでないものがあるようです。
- 仕様でしょうか。

**Comment by yuki-takei** [comment]
@takuma-watanabe 現状、これらの挙動は markdown レンダリングエンジン(marked)に依拠してしまうので、「仕様です」ということになるかもしれませんね…

ただ、HackMD は markdown-it というものを使っているのですが、以下のようになりました。

https://hackmd.io/s/HJupcATNz#

同様にリストは描画されないものの、テーブルとコードブロックは marked よりましなようです。

**Comment by takuma-watanabe** [comment]
@yuki-takei ご確認ありがとうございました。
なるほど！仕様ということで諦めます。

＃とはいえ、markdown-it では、もう少し対応が出来るという情報のおかげで…若干心残りが。

**Comment by yuki-takei** [comment]
#64 着手時にチェックします。(いつ着手できるかはまだ見通し立っていませんが…)

**Comment by takuma-watanabe** [comment]
可能性を残して頂き、ありがとうございます！
気長に待ってます。
