### ISSUE TITLE
imprv:新規ページ作成時の補完機能

### ISSUE THREAD

**Issue by Tatsuki-I** [weseek/crowi-plus#238]
新規ページ作成時の`/以下にページを作成`にパスを入力する際に既に存在する階層についてIDEの補完機能のように候補を出す機能があると嬉しいです.

動作的にはSlackで見せて頂いたgifのものが理想通りです.
機能ですが, 以下の2つがあると有難いです(検索機能の機能的に難しいなら以下は無視して頂いて構いません).

- 前方一致ではなくても候補に出る
  - 例:"/Foobar/"という階層に対して, "bar"と入力しても候補に出るような機能
- 大文字小文字や全角半角が一致しなくても候補に出る
  - 例:"/Foobar/"という階層に対して, "foobar"や"Ｆｏｏｂａｒ"と入力しても候補に出るような機能

以上です.
よろしくお願いします.

**Comment by ryu-sato** [comment]
ブランチ `imprv/enable-new-page-name-input-box-to-searchable` で対応します。

**Comment by yuki-takei** [comment]
@Tatsuki-I master ブランチにはマージしました。次回リリースをお待ちください。

**Comment by Tatsuki-I** [comment]
ありがとうございます
