### ISSUE TITLE
Imprv: Enter key doesn't work on "Create page under:"

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#250]
![image](https://user-images.githubusercontent.com/1638767/35506570-0e6641ec-052d-11e8-8792-f32b2324fb0f.png)

Environment
------------

### Host

| item     | version |
| ---      | --- |
|crowi-plus|2.3.8-RC [9ed0fc4]|

### Client

| item     | version |
| ---      | --- |
|OS        |Win 10|
|browser   |Firefox 58.0 64bit|

How to reproduce? (再現手順)
---------------------------

1. Open "New Page" popup
1. Enter `/hoge` to "Create page under: " input
1. Press <kbd>Enter</kbd>

What happens? (症状)
---------------------

- Nothing happens

What is the expected result? (期待される動作)
-------------------------------------------

- Go to `/hoge` page to edit

**Comment by yuki-takei** [comment]
フォーカス関連に課題

- [ ] ページリロード時に HeaderSearchBox にフォーカスが当たってしまう
- [ ] Create Page ポップアップの挙動に一貫性を

**Comment by ryu-sato** [comment]
ブランチ `imprv/250-doesnot-focus-on-input-box` で対応し、PR #253 を出しました。
input box にフォーカスをあてる処理を削除したので、ページリロード時に HeaderSearchBox にフォーカスは当たらないようになり、Create Page ポップアップの挙動は元に戻りました。
