### ISSUE TITLE
Imprv: `Ctrl-S` でページ更新後、ページ閲覧タブに戻っても変更が反映されていない

### ISSUE THREAD

**Issue by Tatsuki-I** [weseek/crowi-plus#255]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Centos7|
|crowi-plus|2.3.8|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac, Windows|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. ページ編集タブへ
1. <kbd>Ctrl-S</kbd> で保存
1. 閲覧タブ(魔法の杖アイコン)をクリック

What happens? (症状)
---------------------

1. 閲覧画面に戻っても更新が反映されておらず、ブラウザで更新をしないといけない

What is the expected result? (期待される動作)
-------------------------------------------

魔法の杖アイコンを押すと更新済の画面が表示される.

**Comment by yuki-takei** [comment]
@Tatsuki-I 報告ありがとうございます。
`imprv/replace-renderer` ブランチで対応します。

**Comment by yuki-takei** [comment]
master ブランチに修正を反映しました。変更が多いので、自社でちょっとテストしてからリリースします。もうしばらくお待ちください。
