### ISSUE TITLE
Feature: Custom Header

### ISSUE THREAD

**Issue by kazuemon** [weseek/crowi-plus#259]
Google AnalyticsなどをHEADタグに挿入するためのカスタマイズ設定ができるようにしてほしいです。

**Comment by kazuemon** [comment]
要望をどのように送ればよいかわからなかったのでこの形で投稿させていただきました。

**Comment by yuki-takei** [comment]
@kazuemon 
実装されました。v2.4.1 リリースをお待ちください。
