### ISSUE TITLE
TypeError: Cannot read property 'js' of undefined

### ISSUE THREAD

**Issue by trisland** [weseek/crowi-plus#264]
Environment
----

### Host

| item | version |
| - | - |
| CentOS | 7.4 |
| crowi-plus | 2.4.0-RC |
| node.js | 6.13.0 |
| npm | 5.6.0 |
| Using Docker | no |
| Using [crowi-plus-docker-compose][crowi-plus-docker-compose] | no |

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item | version |
| - | - |
| Windows 10 | Fall Creators Update |
| Google Chrome | 63.0.3239.132 |

How to reproduce? (再現手順)
---------------------------

1. 環境構築
   ```bash
   yum install nodejs yarn git mongodb-org{,-server}
   npm install -g npm && npm update -g
   ```

1. データベース用意
   ```bash
   systemctl start mongod
   mongo
   ```

   ```mongo
   use crowidb
   db.createUser({user: "crowi", pwd: "DB-PASSWD", roles: [{role: "readWrite", db: "crowidb"}]})
   ```
1. インストール
   ```bash
   cd /var/lib
   git clone --depth=1 https://github.com/weseek/crowi-plus
   
   cd crowi-plus
   yarn install
   ```

1. 起動
   ```bash
   MONGO_URI="mongodb://crowi:DB-PASSWD@localhost/crowidb" npm start
   ```

What happens? (症状)
----
以下のエラーが出力されます。
```
TypeError: Cannot read property 'js' of undefined
    at Object.eval [as tpl] (eval at <anonymous> (/usr/share/nginx/crowi-plus/node_modules/swig-templates/lib/swig.js:497:13), <anonymous>:19:150)
    at compiled (/usr/share/nginx/crowi-plus/node_modules/swig-templates/lib/swig.js:618:18)
    at /usr/share/nginx/crowi-plus/node_modules/swig-templates/lib/swig.js:558:20
    at /usr/share/nginx/crowi-plus/node_modules/swig-templates/lib/swig.js:689:9
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

What is the expected result? (期待される動作)
----
- 初回の管理画面が表示されるのでしょうか…

**Comment by yuki-takei** [comment]
@trisland 
まず npm のバージョンですが、5系はまだサポート対象外ですので、
https://github.com/weseek/crowi-plus/blob/master/README.md#dependencies
に則って4系での動作確認をお願いします。

それからご利用の crowi-plus のバージョンに関しても、2.4.0-RC はまだリリース前ですのでいろいろ不具合があることが予想されます。一旦 2.3.8 で試してみていただけますでしょうか。

よろしくお願いします。

**Comment by trisland** [comment]
@yuki-takei 様
早速お返事いただきありがとうございます。

`npm`のバージョンを4.6.1に変更したところ、2.3.8, 2.4.0-RCともにインストールが完了することを確認いたしました。
不勉強からお騒がしてしまい大変申し訳ございません。
引き続きどうぞよろしくお願いいたします。

**Comment by yuki-takei** [comment]
@trisland いいえー。お疲れさまでした。
