### ISSUE TITLE
Internet Exploreでのテキストボックス不具合

### ISSUE THREAD

**Issue by yu-i123** [weseek/crowi-plus#271]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CextOS7|
|crowi-plus|2.3.8|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Internet Explore 11.0.51|

How to reproduce? (再現手順)
---------------------------

1. "Search"や新規ページ作成画面でテキストボックスをクリック

What happens? (症状)
---------------------

- 一瞬だけ入力を受け付けるが、すぐにテキストボックスの入力受付状態が外れる

What is the expected result? (期待される動作)
-------------------------------------------

- 他をクリックするまで入力受付状態が続く

Note
----

- Internet Exploreでは上記現象が発生しましたが、FireFoxでは発生しませんでした。
- ページの内容編集では、上記現象は発生しませんでした。

**Comment by yuki-takei** [comment]
@yu-i123 ご報告ありがとうございます。
申し訳ないのですが現状IE11は動作環境としてサポート外となっておりますので、この issue はこちらで対応を行わず close させていただきます。

ただコントリビュートは受け付けますので、もし「こうすれば動くよ」みたいなのがありましたら、引き続き情報やコードの寄与をいただければと思います。
