### ISSUE TITLE
Bug: コードのシンタックスハイライト時、未対応言語場合にファイル名が表示されない

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#273]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.4.0|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](crowi-plus-docker-compose)|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

How to reproduce? (再現手順)
---------------------------

1. 以下のように記載したページを作成する。
<pre>
```yaml:data.yml
filename: not_displayed
```
</pre>

What happens? (症状)
---------------------

- ファイル名が表示されない

![image](https://user-images.githubusercontent.com/32568002/36412626-5d369000-165e-11e8-8290-a2c36c6c4a66.png)

What is the expected result? (期待される動作)
-------------------------------------------

- シンタックスハイライトに対しファイル名が表示される

Note
----

- ruby ではファイル名が表示されました。言語による違いがあるのでしょうか。
- デモサイトの以下のページで確認可能です。
/Sandbox/hilight_test
https://demo.crowi-plus.org/5a8bd30c6cf1e900242e0f78
- よく見たら、そもそも yaml はシンタックスハイライトもされていないように見えます。

**Comment by yuki-takei** [comment]
@takuma-watanabe 
コードのシンタックスハイライトは、[highlight.js Demo](https://highlightjs.org/static/demo/) の common カテゴリ内の言語に対応しています。

その他の言語に関しては crowi-plus 側デフォルトでどこまで広げるのかというのは迷うところです。時流を反映させるとすれば、個人的には Dockerfile, Gradle, SCSS, Scala, Swift, TypeScript あたりも欲しいなと思うのですが、他にも Basic, Erlang, Haskell, R も入れる？とか…キリがなくなるんですね。

v2.4.1 でカスタムヘッダの設定が可能になるのですが、そちらで CDN を参照するコードを入れたりしてどうにかならないかなとか考えています。

**Comment by takuma-watanabe** [comment]
@yuki-takei 
なるほど！大変失礼しました。common カテゴリに限定している点を見逃してました。
v2.4.1 のカスタムヘッダ機能がリリースされたら、私も試してみたいと思います。

**Comment by yuki-takei** [comment]
実験完了。
こういうのをカスタムヘッダに書けばハイライト効くようになります。

```html
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.12.0/build/languages/yaml.min.js" defer></script>
```

**Comment by takuma-watanabe** [comment]
@yuki-takei ありがとうございます！
v2.4.1 のリリースお待ちしてます。
