### ISSUE TITLE
Bug: PlantUML で日本語を含む図が描画されない

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#274]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.4.0|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](crowi-plus-docker-compose)|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

How to reproduce? (再現手順)
---------------------------

1. PlantUMLを日本語を含めて記載する

```
@startuml
太郎 -> 花子 :こんにちは
@enduml
```

What happens? (症状)
---------------------

- エラーとなり描画されない

![image](https://user-images.githubusercontent.com/32568002/36417649-d44c9ebc-166f-11e8-81ff-a0b0f86d2420.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 日本語を含めて描画してほしい

Note
----

- 以下のデモサイトで再現可能です
/Sandbox/plantuml_test
https://demo.crowi-plus.org/5a8bec226cf1e900242e0f7b
- v2.3.9 までは描画されていたと思います

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございます。再現確認しました。v2.4.1 で修正します。
