### ISSUE TITLE
Bug: インラインに$を入れると記事内容がループする。

### ISSUE THREAD

**Issue by izmth** [weseek/crowi-plus#285]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | centOS7|
|crowi-plus|2.4.1|
|node.js   |6.12.1|
|npm       |4.6.1|
|Using Docker|no|
|Using [crowi-plus-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        | ubuntu16.04|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------
`インライン`の中に$を入れる  
シンタックスハイライトでも同様  

What is the expected result? (期待される動作)
-------------------------------------------
単純に、$がインラインの中に表示される

デモサイトでも発生、https://demo.crowi-plus.org/Sandbox/%E3%83%89%E3%83%AB%E3%83%9E%E3%83%BC%E3%82%AF
![screenshot from 2018-03-01 04-35-35](https://user-images.githubusercontent.com/28652907/36809029-1f6bc86e-1d0a-11e8-9651-ce25a2c57f9d.png)

**Comment by yuki-takei** [comment]
@izmth ご報告ありがとうございます。再現は確認しました。

まだ調査はしていないのですが、なんとなく思い当たる節はあります…
進捗がありましたらまた報告させていただきます。

**Comment by yuki-takei** [comment]
@izmth 原因特定完了し、先ほど修正を push しました。
次回リリースの v2.4.2 で直るはずです。今しばらくお待ちください。
