### ISSUE TITLE
Comment count not being updated when a comment of a page is deleted

### ISSUE THREAD

**Issue by hitochan777** [weseek/crowi-plus#288]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|crowi-plus|2.4.2RC|
|node.js   |6.13.0|
|npm       |3.10.10|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu16.04|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. Add a comment in a page. You can see that the comment count (in this case 1) next to the path to the page.
1. Delete the comment.
1. Reload the page, and you can see that the comment count is NOT zero. You can also see this phenomenon in the portal.
 
What happens? (症状)
---------------------
- Comment count not being updated when a comment of a page is deleted

What is the expected result? (期待される動作)
-------------------------------------------

- Comment count should also be updated when a comment is deleted.

**Comment by hitochan777** [comment]
#286

**Comment by hitochan777** [comment]
#286

**Comment by yuki-takei** [comment]
fixed by #286
