### ISSUE TITLE
Bug: テンプレート機能が正常に機能しない

### ISSUE THREAD

**Issue by typestar-y** [weseek/crowi-plus#303]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|crowi-plus|2.4.3|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Chrome65|

How to reproduce? (再現手順)
---------------------------

1. ページを作成する
1. 以下のようにテンプレート作成ページを記述する
1. 作成したページのテンプレート作成ボタンをクリックする
    ~~~
    ```template:/user/guest1/{date}/template_output
    # 見出し1
    内容
    # 見出し2
    内容
    ```
    ~~~

What happens? (症状)
---------------------

- 何も起きない

What is the expected result? (期待される動作)
-------------------------------------------

- 新規ページ作成画面が表示される

notes
----------
https://demo.crowi-plus.org/user/guest1/%E3%83%A1%E3%83%A2/2018/03/13/template_test

**Comment by yuki-takei** [comment]
@typestar-y ご報告ありがとうございます。再現は確認しておりますので、折を見て修正をいたします。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@typestar-y 修正を完了し、master ブランチにマージしました。次回リリースをお待ちください。

**Comment by typestar-y** [comment]
素早いご対応ありがとうございます！
