### ISSUE TITLE
Bug: tsv記法での表表示が機能しない

### ISSUE THREAD

**Issue by typestar-y** [weseek/crowi-plus#306]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|crowi-plus|2.4.3|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Chrome65|

How to reproduce? (再現手順)
---------------------------

1. ページを作成する
1. 以下のような内容を記述する

```tsv
ヘッダー1	ヘッダー2
あいう	えお
```

What happens? (症状)
---------------------

- コードがそのまま画面に表示される

What is the expected result? (期待される動作)
-------------------------------------------

- 表形式で表示される

notes
----------
https://demo.crowi-plus.org/user/guest1/%E3%83%A1%E3%83%A2/2018/03/14/tsv-test

**Comment by yuki-takei** [comment]
@typestar-y 挙げていただいた issue に関してですが、v2.4.0 で markdown-it を採用して以降記法が変わっております。(特にその辺りのドキュメントがなく、不親切で申し訳ないです)

デモサイトの Sandbox に example がありますので、こちらで置き換えてください。
https://demo.crowi-plus.org/Sandbox#tsv-crowi-plus-%E7%8B%AC%E8%87%AA%E8%A8%98%E6%B3%95

上記によって、本家 Crowi とは上記部分に関しては互換性が完全であるとは言えなくなってしまったのですが、CSV に対応するなどの機能追加もありますので、ご容赦いただければと思います。

**Comment by typestar-y** [comment]
@yuki-takei ご丁寧にレスいただきありがとうございます。ドキュメントちゃんと読めていなくて申し訳ありません。。教えていただきました方法で解決しました。ありがとうございました
