### ISSUE TITLE
Imprv: enhanced layout

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#31]
サイドバー解体
----------------

基本 esa.io 風に

- 作成者・作成日・更新日時、いいね、みた人
  - ページ内ヘッダに移動
- コメント
  - ページ最下部に展開
  - ![image](https://cloud.githubusercontent.com/assets/1638767/25046281/8e43efaa-216b-11e7-93d3-9af8445665bb.png)

**Comment by yuki-takei** [comment]
途中経過
---------

![image](https://cloud.githubusercontent.com/assets/1638767/26035749/361d7112-390c-11e7-817d-4c2fcc140ce5.png)

レイアウト崩れ対応の対象箇所
-------------------------------

- https://github.com/weseek/crowi-plus/blob/feat/custom-layout/lib/views/crowi-plus/widget/comments.html
- https://github.com/weseek/crowi-plus/blob/feat/custom-layout/resource/css/_comment_crowi-plus.scss

**Comment by Angola** [comment]
間違えてcloseしてしまった・・・

**Comment by Angola** [comment]
![crowi-plus-comment](https://cloud.githubusercontent.com/assets/3826013/26173818/2e46b2cc-3b88-11e7-80ce-aaa3f4b62b83.png)
修正完了。

**Comment by Angola** [comment]
![comment](https://cloud.githubusercontent.com/assets/3826013/26256187/1bc98fb4-3cf7-11e7-939a-951f237cd1d3.png)
修正完了

**Comment by yuki-takei** [comment]
![image](https://cloud.githubusercontent.com/assets/1638767/26274949/d48ea220-3d90-11e7-9d7a-1bdc5809baaa.png)

めっちゃ細かいけど…三角形の分だけ青いハイライトが削られている

**Comment by yuki-takei** [comment]
一旦 close する。新しい新規作成ページとタイムライン OFF オプションは別の issue に分割する。
