### ISSUE TITLE
Bug: SMTP設定のユーザ・パスワード欄に、Crowiアカウントの自動補完が勝手にされる

### ISSUE THREAD

**Issue by tats-u** [weseek/crowi-plus#318]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04 (Host of Docker)|
|crowi-plus|2.4.4|
|node.js  |6.12.3|
|npm       |4.6.1|
|Using Docker|🙆|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|🙆|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 17.10
|browser   |Firefox 59.0.2|

How to reproduce? (再現手順)
---------------------------

1. 管理者権限のあるアカウントでログイン
1. ログイン時にアカウントのメールアドレス・パスワードをブラウザに保存
1. SMTP設定の「ユーザー」「パスワード」の欄が空でない場合、空にして設定更新

What happens? (症状)
---------------------

- ブラウザに保存したユーザのメールアドレス・パスワードが勝手にSMTP設定の該当欄に入力されてしまいます

What is the expected result? (期待される動作)
-------------------------------------------

- メールアドレス・パスワードが空の時は、該当欄も空でなければなりません

Note
----

- 当該欄のname属性を変えるか、自動補完を無効にすればよいかと思います

**Comment by yuki-takei** [comment]
@tats-u 
ご報告いただいている症状ですが、

> ブラウザに保存したユーザのメールアドレス・パスワードが勝手にSMTP設定の該当欄に入力されてしまいます

というのは、`/admin/app` にアクセスし、以下のような状況でユーザー名を選んだ場合にパスワードも入ってしまうということでしょうか？

![default](https://user-images.githubusercontent.com/1638767/38240581-eab63fb6-376a-11e8-88c4-18b8d96b5b19.png)

もしそうであれば、一般的なブラウザの挙動だと思います。(input の name がそもそもログイン画面のそれとかぶっているのがうっとおしい、という議論は一旦置いておくとして)

そうではなく、ページがロードされた時には既に入っているという状況であれば、それは OS やブラウザ、あるいはアドオンによる利用環境に応じた挙動の違いであるような気がします。

因みに手元では Win 10 + Firefox 59.0.1 でテストし、上記で「一般的なブラウザの挙動ではないか」とコメントした動きになっています。

**Comment by tats-u** [comment]
その通りです。こちらでも調べてみましたが、~ブラウザの挙動がおせっかいすぎて~対処法がないみたいなので、当面の間Closeします。
