### ISSUE TITLE
store images for README.md

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#323]

**Comment by yuki-takei** [comment]
![logo-with-letter](https://user-images.githubusercontent.com/1638767/38253488-be588646-3791-11e8-8eb6-7d1853e0f0c7.png)

**Comment by yuki-takei** [comment]
![logo-with-letter](https://user-images.githubusercontent.com/1638767/38253722-5a7be4d2-3792-11e8-83b5-79e21e1fec37.png)

**Comment by yuki-takei** [comment]
![logo-with-letter](https://user-images.githubusercontent.com/1638767/38254268-d4476bbe-3793-11e8-964c-8865d690baff.png)

**Comment by TsuyoshiSuzukief** [comment]
![growi_wiki_gif](https://user-images.githubusercontent.com/42988650/70407506-f154e000-1a87-11ea-8fd1-f137ceee29cf.gif)

**Comment by TsuyoshiSuzukief** [comment]
![en_growi_gif](https://user-images.githubusercontent.com/42988650/70596967-7c6ddb80-1c2a-11ea-8009-c0ef016b5ae0.gif)
