### ISSUE TITLE
Bug: Top menu is not shown properly

### ISSUE THREAD

**Issue by kelaductor** [weseek/crowi-plus#79]
Environment
------------

- [OS] iOS 10.3(iPhone SE)
- [crowi-plus] 1.1.9
- [node.js] 6.10.3
- [browser] Google Chrome for iOS

How to reproduce? (再現手順)
---------------------------

Access the top page

What's happen? (症状)
---------------------
Search bar and the hamburger menu are unexpectedly merged
![img_2713](https://cloud.githubusercontent.com/assets/20236173/26537090/62d144c4-4477-11e7-9dd7-ac774655f9e6.PNG)
![img_2712](https://cloud.githubusercontent.com/assets/20236173/26537088/62bcbb26-4477-11e7-8931-c201df0d06ed.PNG)
![img_2711](https://cloud.githubusercontent.com/assets/20236173/26537089/62cd27ea-4477-11e7-8785-6b91e7b0c7ac.PNG)

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------

![2017-05-29 14 04 40](https://cloud.githubusercontent.com/assets/20236173/26537150/e4d7a94a-4477-11e7-9b9e-ac06038e4e25.png)

Note
----

**Comment by yuki-takei** [comment]
Fixed at master branch.
Look forward to next release.
