### ISSUE TITLE
Bug: all strings appear on presentation mode

### ISSUE THREAD

**Issue by skomma** [weseek/crowi-plus#96]
Environment
------------

- [OS] Win10/Mac
- [crowi-plus] 1.1.10
- [node.js] 6.10.3
- [browser] Firefox 50.1.0/Chrome 58.0

How to reproduce? (再現手順)
---------------------------

1. create a new page and save
1. go to presentation mode

![crowi_presentation_mode_issue](https://user-images.githubusercontent.com/4454401/27112222-94f95fec-50f0-11e7-9a15-65a446c95910.gif)

What happens? (症状)
---------------------

- all strings appear in the page

What is the expected result? (期待される動作)
-------------------------------------------

- only strings of the first header appear

Note
-----

- This issue occurs only when the first time switching to presentation mode after page has loaded.
- When focusing presentation screen and pressing Esc twice, presentation screen is displayed as expected.

**Comment by yuki-takei** [comment]
I confirmed this occurs when using crowi v1.2.2.
